import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, '..', 'data')
EMBEDDINGS_DIR = os.path.join(DATA_DIR, 'embeddings')
REPORTS_DIR = os.path.join(DATA_DIR, 'reports')
DATABASE_PATH = os.path.join(BASE_DIR, '..', 'attendance.db')

DETECTION_MODEL = 'buffalo_l'
SIMILARITY_THRESHOLD = 0.35
EMBEDDING_SIZE = 512
CONFIDENCE_THRESHOLD = 0.30

FRAME_WIDTH = 640
FRAME_HEIGHT = 480

PREPROCESS_ENABLED = True
PREPROCESS_RESIZE = (FRAME_WIDTH, FRAME_HEIGHT)
PREPROCESS_GAMMA = 1.1
PREPROCESS_CONTRAST = 1.1
PREPROCESS_BRIGHTNESS = 10
PREPROCESS_GAUSSIAN_KERNEL = 3

ATTENDANCE_COOLDOWN_MINUTES = 60


# vim: ts=4:et
